"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {Challenge,createSnapshot,dictionary,enterChallenge,evaluate,Evaluation,greedy,MEANINGS,nextChallenge,rollingAccuracy,Snapshot,softmax,TOKENS,trainBatch} from "./babel";
const arrows=["↑","↗","→","↘","↓","↙","←","↖"];
type Mission={text:string;target?:number;token?:number;received?:number;action?:number;success?:boolean;message:string};
type Plan={challenge:Challenge;summary:string[]};

function AccuracyChart({snapshot,chance}:{snapshot:Snapshot;chance:number}){const w=520,h=132,p=snapshot.chart,min=p[0]?.episode??0,max=p.at(-1)?.episode??1,x=(v:number)=>8+(v-min)/Math.max(1,max-min)*(w-16),y=(v:number)=>h-8-v/100*(h-16),line=p.map(v=>`${x(v.episode)},${y(v.accuracy)}`).join(" ");return <div className="chart-wrap"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Rolling task accuracy"><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#87f7c7" stopOpacity=".34"/><stop offset="100%" stopColor="#87f7c7" stopOpacity="0"/></linearGradient></defs>{[chance,50,75,100].map((v,i)=><g key={i}><line x1="0" y1={y(v)} x2={w} y2={y(v)} className="grid-line"/><text x="8" y={y(v)-4} className="axis-label">{Math.round(v)}%</text></g>)}{p.length>1&&<><polygon points={`${x(p[0].episode)},${h} ${line} ${x(p.at(-1)!.episode)},${h}`} fill="url(#chartFill)"/><polyline points={line} className="accuracy-line"/></>}</svg></div>}
function Bars({values,labels}:{values:number[];labels:readonly string[]}){return <div className="probability-bars">{values.map((v,i)=><div className="probability-row" key={i}><span>{labels[i]}</span><div className="bar-track"><i style={{width:`${Math.max(2,v*100)}%`}}/></div><b>{Math.round(v*100)}%</b></div>)}</div>}

export default function Home(){
 const [snapshot,setSnapshot]=useState<Snapshot>(()=>createSnapshot(81527)),[challenge,setChallenge]=useState<Challenge>({level:1,meaningCount:2,tokenCount:2,channelNoise:0,rewardNoise:0,mastery:92}),[running,setRunning]=useState(false),[speed,setSpeed]=useState(120),[rate,setRate]=useState(.16),[temperature,setTemperature]=useState(.82),[selectedTrace,setSelectedTrace]=useState(0),[evaluation,setEvaluation]=useState<Evaluation[]>([]),[showMethod,setShowMethod]=useState(false),[autoArchitect,setAutoArchitect]=useState(false),[directive,setDirective]=useState("When the protocol is mastered, add one new meaning. Preserve old capabilities and keep the frontier difficult but solvable."),[plan,setPlan]=useState<Plan|null>(null),[history,setHistory]=useState<{level:number;score:number;challenge:string}[]>([]),[missionText,setMissionText]=useState("Go north"),[mission,setMission]=useState<Mission|null>(null);
 const frameRef=useRef<number|null>(null),lastAdvance=useRef(-1);
 const train=useCallback((count:number)=>setSnapshot(s=>trainBatch(s,count,rate,temperature,challenge)),[rate,temperature,challenge]);
 useEffect(()=>{if(!running)return;const loop=()=>{train(speed);frameRef.current=requestAnimationFrame(loop)};frameRef.current=requestAnimationFrame(loop);return()=>{if(frameRef.current)cancelAnimationFrame(frameRef.current)}},[running,speed,train]);
 const accuracy=rollingAccuracy(snapshot),chance=100/challenge.meaningCount,lexicon=useMemo(()=>dictionary(snapshot,challenge),[snapshot,challenge]),trace=snapshot.traces[selectedTrace]??snapshot.traces[0],latest=snapshot.traces[0],distinct=new Set(lexicon.map(i=>i.tokenIndex)).size,mastered=snapshot.recent.length>=250&&accuracy>=challenge.mastery&&distinct===challenge.meaningCount,proof=mastered?"MASTERY VERIFIED":accuracy>=Math.max(45,chance+15)?"CONVENTION FORMING":"NO LANGUAGE YET";

 const applyChallenge=useCallback((next:Challenge)=>{setHistory(h=>[{level:challenge.level,score:accuracy,challenge:`${challenge.meaningCount} meanings · ${Math.round(challenge.channelNoise*100)}% noise`},...h].slice(0,12));setChallenge(next);setSnapshot(s=>enterChallenge(s));setEvaluation([]);setMission(null);setPlan(null);setSelectedTrace(0);lastAdvance.current=snapshot.episodes;},[accuracy,challenge,snapshot.episodes]);
 useEffect(()=>{if(autoArchitect&&mastered&&snapshot.episodes!==lastAdvance.current){const next=nextChallenge(challenge);applyChallenge(next)}},[autoArchitect,mastered,snapshot.episodes,challenge,applyChallenge]);

 const askArchitect=()=>{const text=directive.toLowerCase();let next={...challenge,level:challenge.level+1},changes:string[]=[];
  const noise=text.match(/(?:noise|corruption|corrupt)[^\d]*(\d{1,2})\s*%/),mastery=text.match(/mastery[^\d]*(\d{2,3})\s*%/),add=text.match(/add\s+(\d+)\s+(?:new\s+)?(?:meaning|target)/);
  if(add){const n=+add[1];next.meaningCount=Math.min(8,next.meaningCount+n);next.tokenCount=Math.max(next.tokenCount,next.meaningCount);changes.push(`Add ${next.meaningCount-challenge.meaningCount} grounded meaning(s)`)}
  if(/add (?:one|another|a) (?:new )?(?:meaning|target)/.test(text)){next.meaningCount=Math.min(8,next.meaningCount+1);next.tokenCount=Math.max(next.tokenCount,next.meaningCount);changes.push("Add one grounded meaning")}
  if(noise){next.channelNoise=Math.min(.45,+noise[1]/100);changes.push(`Set channel corruption to ${noise[1]}%`)}
  if(mastery){next.mastery=Math.max(55,Math.min(100,+mastery[1]));changes.push(`Require ${next.mastery}% mastery`)}
  if(/reduce|fewer symbols|scarce/.test(text)){next.tokenCount=Math.max(2,next.tokenCount-1);changes.push("Reduce available vocabulary by one symbol")}
  if(/brutal|much harder|extreme/.test(text)){next.meaningCount=Math.min(8,next.meaningCount+2);next.tokenCount=Math.max(next.tokenCount,next.meaningCount);next.channelNoise=Math.min(.35,next.channelNoise+.08);next.rewardNoise=Math.min(.15,next.rewardNoise+.03);changes.push("Add two meanings","Increase signal and feedback corruption")}
  if(/easier|back off|simpler/.test(text)){next.channelNoise=Math.max(0,next.channelNoise-.05);next.rewardNoise=Math.max(0,next.rewardNoise-.02);next.mastery=Math.max(70,next.mastery-5);changes.push("Reduce corruption and lower the gate")}
  if(!changes.length){next=nextChallenge(challenge);changes=["Apply the next frontier mutation automatically"]}
  setPlan({challenge:next,summary:changes});
 };
 const reset=()=>{setRunning(false);setSnapshot(createSnapshot(Math.floor(Math.random()*9e6)));setChallenge({level:1,meaningCount:2,tokenCount:2,channelNoise:0,rewardNoise:0,mastery:92});setEvaluation([]);setHistory([]);setMission(null)};
 const test=(mode:Evaluation["mode"])=>setEvaluation(cur=>[evaluate(snapshot,challenge,mode),...cur.filter(i=>i.mode!==mode)]);
 const runMission=()=>{const normalized=missionText.toUpperCase().replace(/[ -]/g,"");let target=-1;for(let i=challenge.meaningCount-1;i>=0;i--){if(normalized.includes(MEANINGS[i])){target=i;break}}if(target<0){setMission({text:missionText,message:"Unsupported or ambiguous: use an active direction shown in the world."});return}const token=greedy(softmax(snapshot.sender[target].slice(0,challenge.tokenCount),.12)),received=Math.random()<challenge.channelNoise?Math.floor(Math.random()*challenge.tokenCount):token,action=greedy(softmax(snapshot.receiver[received].slice(0,challenge.meaningCount),.12));setMission({text:missionText,target,token,received,action,success:action===target,message:action===target?"Instruction executed.":"Protocol produced the wrong action."})};

 return <main><header className="topbar"><div className="brand"><span className="brand-mark">B</span><div><strong>BABEL</strong><small>INFINITE LANGUAGE GROUND</small></div></div><div className="status-strip"><span className="local-dot"/> LOCAL COMPUTE <span className="divider"/> SEED {snapshot.seed}</div></header>
 <section className="hero"><div><p className="eyebrow">FRONTIER {challenge.level} · {challenge.meaningCount} MEANINGS · {challenge.tokenCount} SYMBOLS</p><h1>Grow a language.<br/><em>Then speak to it.</em></h1><p className="lede">A persistent population learns symbols, survives harder channel conditions, and eventually translates your instructions into its own protocol.</p></div><div className={`proof ${mastered?"proved":""}`}><span>CAPABILITY GATE</span><strong>{proof}</strong><small>{accuracy.toFixed(1)}% / {challenge.mastery}% required</small></div></section>

 <section className="architect-grid">
  <article className="panel architect-panel"><div className="panel-head"><div><span>00</span><h2>CURRICULUM ARCHITECT</h2></div><label className="auto-switch"><input type="checkbox" checked={autoArchitect} onChange={e=>setAutoArchitect(e.target.checked)}/><i/>AUTO-ADVANCE</label></div><div className="architect-body"><div><span className="micro-label">DIRECT THE AGENT</span><textarea value={directive} onChange={e=>setDirective(e.target.value)} aria-label="Curriculum architect directive"/><div className="prompt-row"><button onClick={askArchitect} className="primary">PROPOSE NEXT FRONTIER</button><button onClick={()=>{setDirective("Make it brutal: add two targets, increase corruption, and preserve old capabilities.");setPlan(null)}}>LOAD HARD MODE</button></div></div><div className="genome"><span className="micro-label">ACTIVE CHALLENGE GENOME</span><div><b>{challenge.meaningCount}</b><small>MEANINGS</small></div><div><b>{challenge.tokenCount}</b><small>SYMBOLS</small></div><div><b>{Math.round(challenge.channelNoise*100)}%</b><small>CHANNEL NOISE</small></div><div><b>{Math.round(challenge.rewardNoise*100)}%</b><small>FEEDBACK NOISE</small></div></div></div>
  {plan&&<div className="proposal"><div><span>ARCHITECT PROPOSAL</span>{plan.summary.map(x=><b key={x}>+ {x}</b>)}</div><div><button onClick={()=>setPlan(null)}>REJECT</button><button className="primary" onClick={()=>applyChallenge(plan.challenge)}>APPLY WITHOUT RESETTING MODELS</button></div></div>}
 </article>
 </section>

 <section className="lab-grid"><article className="panel world-panel"><div className="panel-head"><div><span>01</span><h2>TRAINING WORLD</h2></div><span className="live-tag"><i/> {running?"TRAINING":"PAUSED"}</span></div><div className="world">
  {MEANINGS.slice(0,challenge.meaningCount).map((meaning,i)=>{const angle=-Math.PI/2+i*Math.PI*2/challenge.meaningCount;return <div className={`chamber ${latest?.target===i?"target":""} ${latest?.action===i?"chosen":""}`} style={{left:`${50+40*Math.cos(angle)}%`,top:`${50+39*Math.sin(angle)}%`,transform:"translate(-50%,-50%)"}} key={meaning}><span>{arrows[i]}</span><small>{meaning}</small></div>})}
  <div className="sender agent"><span>S</span><small>SEES TARGET</small></div><div className="receiver agent"><span>R</span><small>CHOOSES</small></div>{latest&&<div className="signal" key={latest.id}><span>{TOKENS[latest.sent]}</span><small>{latest.received!==latest.sent?"CORRUPTED":"MESSAGE"}</small></div>}<div className="world-caption">{latest?(latest.success?<><b>COORDINATION SUCCESS</b> Receiver chose {MEANINGS[latest.action]}</>:<><b className="miss">COORDINATION FAILED</b> Target was {MEANINGS[latest.target]}</>):"Start training to observe the first exchange."}</div>
 </div><div className="controls"><button className="primary" onClick={()=>setRunning(v=>!v)}>{running?"PAUSE EVOLUTION":"RUN EVOLUTION"}</button><button onClick={()=>train(1)} disabled={running}>STEP ONCE</button><button onClick={()=>train(2500)}>+2,500 TRIALS</button><button onClick={reset}>NEW CIVILIZATION</button></div><div className="sliders"><label><span>Trials / frame <b>{speed}</b></span><input type="range" min="10" max="500" step="10" value={speed} onChange={e=>setSpeed(+e.target.value)}/></label><label><span>Exploration <b>{temperature.toFixed(2)}</b></span><input type="range" min=".2" max="1.4" step=".02" value={temperature} onChange={e=>setTemperature(+e.target.value)}/></label><label><span>Learning rate <b>{rate.toFixed(2)}</b></span><input type="range" min=".03" max=".3" step=".01" value={rate} onChange={e=>setRate(+e.target.value)}/></label></div></article>
 <aside className="metrics-column"><article className="panel score-panel"><div className="panel-head compact"><div><span>02</span><h2>EVIDENCE</h2></div></div><div className="score-row"><div><strong>{accuracy.toFixed(1)}%</strong><small>ROLLING ACCURACY</small></div><div><strong>{snapshot.episodes.toLocaleString()}</strong><small>LIFETIME TRIALS</small></div></div><AccuracyChart snapshot={snapshot} chance={chance}/><div className="chance-line"><span/> CHANCE = {chance.toFixed(1)}%</div></article>
 <article className="panel ablation-panel"><div className="panel-head compact"><div><span>03</span><h2>BREAK THE LANGUAGE</h2></div></div><p>Frozen trials isolate whether the symbol channel causes the result.</p><div className="ablation-buttons">{(["intact","scrambled","silent"] as const).map(mode=><button key={mode} onClick={()=>test(mode)}><span>{mode==="intact"?"◆":mode==="scrambled"?"⤨":"∅"}</span>{mode.toUpperCase()}</button>)}</div><div className="evaluation-results">{(["intact","scrambled","silent"] as const).map(mode=>{const result=evaluation.find(i=>i.mode===mode);return <div key={mode}><span>{mode}</span><b>{result?`${result.accuracy.toFixed(1)}%`:"—"}</b></div>})}</div></article></aside></section>

 <section className="mission-grid"><article className="panel mission-panel"><div className="panel-head"><div><span>04</span><h2>HUMAN LANGUAGE BRIDGE</h2></div><small>Grounded controlled language · no LLM</small></div><div className="mission-body"><div><span className="micro-label">GIVE THE POPULATION A TASK</span><div className="mission-input"><input value={missionText} onChange={e=>setMissionText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&runMission()} aria-label="Human language mission"/><button className="primary" onClick={runMission}>TRANSLATE & EXECUTE</button></div><small>Try: “Go north,” “Move northeast,” or any direction currently active in the world.</small></div>{mission?<div className={`translation ${mission.success?"passed":""}`}><div><small>YOUR LANGUAGE</small><b>{mission.text}</b></div><span>→</span><div><small>TASK GRAPH</small><b>{mission.target===undefined?"UNRESOLVED":`MOVE(${MEANINGS[mission.target]})`}</b></div><span>→</span><div><small>INTERNAL SIGNAL</small><b>{mission.token===undefined?"—":TOKENS[mission.token]}</b></div><span>→</span><div><small>WORLD ACTION</small><b>{mission.action===undefined?"—":MEANINGS[mission.action]}</b></div><strong>{mission.message}</strong></div>:<div className="translation-empty">The bridge exposes every transformation. It does not claim understanding when the task cannot be grounded.</div>}</div></article>
 <article className="panel history-panel"><div className="panel-head"><div><span>05</span><h2>CAPABILITY LINEAGE</h2></div><small>Models persist across frontiers</small></div><div className="history-list"><div className="current"><span>F{challenge.level}</span><b>ACTIVE FRONTIER</b><small>{challenge.meaningCount} meanings · {Math.round(challenge.channelNoise*100)}% noise</small></div>{history.length?history.map((h,i)=><div key={i}><span>F{h.level}</span><b>{h.score.toFixed(1)}% AT EXIT</b><small>{h.challenge}</small></div>):<p>No mastered frontier has been archived yet.</p>}</div></article></section>

 <section className="lower-grid"><article className="panel lexicon-panel"><div className="panel-head"><div><span>06</span><h2>EMERGENT DICTIONARY</h2></div><small>Inferred · not prescribed</small></div><div className="dictionary">{lexicon.map(item=><div className={`word ${item.meaning===item.interpretedAs?"aligned":""}`} key={item.meaning}><span className="token">{item.token}</span><div><small>SENDER USES FOR</small><strong>{item.meaning}</strong></div><div><small>RECEIVER INTERPRETS</small><strong>{item.interpretedAs}</strong></div><b>{Math.round(Math.min(item.confidence,item.interpretationConfidence))}%</b></div>)}</div></article>
 <article className="panel microscope-panel"><div className="panel-head"><div><span>07</span><h2>DECISION MICROSCOPE</h2></div><small>Exact computation</small></div>{trace?<><div className="trace-picker">{snapshot.traces.slice(0,8).map((item,i)=><button className={selectedTrace===i?"active":""} onClick={()=>setSelectedTrace(i)} key={item.id}>#{item.id} <i className={item.success?"success":"failure"}/></button>)}</div><div className="decision-grid"><div className="decision-card"><span>1 · OBSERVATION</span><strong>{arrows[trace.target]} {MEANINGS[trace.target]}</strong><small>Sender-only input.</small></div><div className="decision-card"><span>2 · MESSAGE POLICY</span><Bars values={trace.senderProbabilities} labels={TOKENS.slice(0,challenge.tokenCount)}/></div><div className="decision-card signal-card"><span>3 · CHANNEL</span><strong>{TOKENS[trace.sent]}</strong><small>{trace.received===trace.sent?"Delivered intact":`Received as ${TOKENS[trace.received!]}`}</small></div><div className="decision-card"><span>4 · ACTION POLICY</span><Bars values={trace.receiverProbabilities} labels={arrows.slice(0,challenge.meaningCount)}/></div></div><div className="counterfactual"><div><span>CAUSAL REPLAY</span><strong>Change only the received symbol.</strong></div><div className="counterfactual-grid">{trace.counterfactuals.map((values,t)=>{const choice=values.indexOf(Math.max(...values));return <div className={t===trace.received?"actual":""} key={t}><span>{TOKENS[t]}</span><b>{arrows[choice]}</b><small>{Math.round(values[choice]*100)}%</small></div>})}</div></div></>:<div className="empty-state">No decision exists in this frontier yet.</div>}</article></section>
 <section className="method"><button onClick={()=>setShowMethod(v=>!v)}><span>EXPERIMENTAL METHOD & LIMITS</span>{showMethod?"−":"+"}</button>{showMethod&&<div><p><b>Persistence.</b> Advancing a frontier preserves every policy weight. New meanings activate previously unused capacity.</p><p><b>Architect.</b> Directives are compiled locally into explicit challenge parameters. This is intentionally not an LLM pretending to understand an unconstrained request.</p><p><b>Language bridge.</b> Human directions compile to testable goals, then pass through the acquired symbol protocol.</p><p><b>Noise.</b> Channel corruption changes the received symbol. Feedback corruption changes the training signal but not the actual outcome.</p><p><b>Current ceiling.</b> This build grounds eight spatial meanings. Objects, attributes, multi-symbol grammar, populations, and cultural transmission are the next model expansions.</p></div>}</section>
 <footer><span>BABEL / INFINITE GROUND 0.2</span><p>No model API. No prescribed vocabulary. Every claim is testable.</p><span>LOCAL FIRST</span></footer></main>
}
