"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import {
  Activation, blankCourse, Car, clamp, cloneNetwork, coachSamples, Control, Course, createNetwork,
  createTeam, createTeamRuntime, Decision, defaultCourse, evaluateTeam, evolveGeneration, H, HelperRole,
  makeCar, MessagePacket, Network, observe, parameterCount, Point, score, Score, SENSOR_SPECS, SensorKind,
  stepCar, stepTeam, targetFor, Team, TeamRuntime, teamParameters, train, varyCourse, W,
} from "./engine";

type Mode = "design" | "teach" | "auto" | "evaluate";
type Tool = "drive" | "gate" | "obstacle" | "start" | "finish" | "erase";
type History = { label: string; score: Score };
type GenerationRow = { generation: number; fitness: number; score: Score; helpers: number; parameters: number; sensor: SensorKind; team: string };
const emptyDecision: Decision = { observation: "Waiting for a run", action: "—", result: "—", reward: 0, update: "No update", inputs: [], outputs: [] };

function useSize<T extends HTMLElement>() {
  const ref = useRef<T | null>(null), [size, setSize] = useState({ w: 0, h: 0 });
  useEffect(() => { if (!ref.current) return; const ro = new ResizeObserver(([e]) => setSize({ w: e.contentRect.width, h: e.contentRect.height })); ro.observe(ref.current); return () => ro.disconnect(); }, []);
  return { ref, size };
}

function CourseCanvas({ course, setCourse, car, runtime, sensor, tool, control, setControl, onManual }: {
  course: Course; setCourse: (c: Course) => void; car: Car; runtime: TeamRuntime; sensor: SensorKind; tool: Tool;
  control: Control; setControl: (c: Control) => void; onManual: () => void;
}) {
  const { ref, size } = useSize<HTMLDivElement>(), canvas = useRef<HTMLCanvasElement | null>(null), drag = useRef(false);
  useEffect(() => {
    const node = canvas.current; if (!node || !size.w) return; const dpr = Math.min(2, devicePixelRatio || 1), h = size.w * H / W; node.width = size.w * dpr; node.height = h * dpr; const x = node.getContext("2d")!; x.scale(dpr * size.w / W, dpr * size.w / W);
    x.fillStyle = "#08100e"; x.fillRect(0, 0, W, H); x.strokeStyle = "rgba(196,255,92,.055)"; x.lineWidth = 1;
    for (let a = 0; a < W; a += 60) { x.beginPath(); x.moveTo(a, 0); x.lineTo(a, H); x.stroke(); }
    for (let b = 0; b < H; b += 60) { x.beginPath(); x.moveTo(0, b); x.lineTo(W, b); x.stroke(); }
    x.strokeStyle = "#2a3935"; x.lineWidth = 3; x.strokeRect(10, 10, W - 20, H - 20);
    course.obstacles.forEach(o => { const g = x.createRadialGradient(o.x, o.y, 4, o.x, o.y, o.r * 1.6); g.addColorStop(0, "rgba(255,98,84,.3)"); g.addColorStop(1, "rgba(255,98,84,0)"); x.fillStyle = g; x.beginPath(); x.arc(o.x, o.y, o.r * 1.6, 0, Math.PI * 2); x.fill(); x.fillStyle = "#1b2220"; x.strokeStyle = "#ff6254"; x.lineWidth = 3; x.beginPath(); x.arc(o.x, o.y, o.r, 0, Math.PI * 2); x.fill(); x.stroke(); });
    const points = [...course.gates, course.finish]; points.forEach((g, i) => { const done = i < car.gate || car.complete; x.strokeStyle = done ? "#c4ff5c" : i === car.gate ? "#ffffff" : "#597069"; x.lineWidth = i === car.gate ? 5 : 3; x.setLineDash(i === points.length - 1 ? [10, 8] : []); x.beginPath(); x.arc(g.x, g.y, g.r, 0, Math.PI * 2); x.stroke(); x.setLineDash([]); x.fillStyle = done ? "#c4ff5c" : "#9aaeaa"; x.font = "700 18px ui-monospace"; x.textAlign = "center"; x.fillText(i === points.length - 1 ? "GOAL" : String(i + 1), g.x, g.y + 6); });
    x.save(); x.translate(course.start.x, course.start.y); x.rotate(course.start.angle); x.strokeStyle = "#65d7ff"; x.lineWidth = 3; x.beginPath(); x.moveTo(-16, -13); x.lineTo(18, 0); x.lineTo(-16, 13); x.closePath(); x.stroke(); x.restore();
    const target = targetFor(course, car); x.strokeStyle = "rgba(196,255,92,.18)"; x.setLineDash([8, 10]); x.beginPath(); x.moveTo(car.x, car.y); x.lineTo(target.x, target.y); x.stroke(); x.setLineDash([]);
    const range = SENSOR_SPECS[sensor].range; if (range) { x.save(); x.translate(car.x, car.y); x.rotate(car.angle); x.strokeStyle = sensor === "lidar" ? "rgba(218,140,255,.25)" : "rgba(101,215,255,.28)"; x.fillStyle = sensor === "lidar" ? "rgba(218,140,255,.035)" : "rgba(101,215,255,.035)"; x.lineWidth = 2; x.beginPath(); if (sensor === "lidar") x.arc(0, 0, range, 0, Math.PI * 2); else { x.moveTo(0, 0); x.arc(0, 0, range, -.62, .62); x.closePath(); } x.fill(); x.stroke(); x.restore(); }
    runtime.messages.slice(0, 2).forEach(m => { const helper = runtime.helpers.find(h => h.id === m.from); if (!helper) return; x.strokeStyle = `rgba(101,215,255,${clamp(.8 - m.age * .35, .12, .8)})`; x.lineWidth = 2; x.setLineDash([6, 7]); x.beginPath(); x.moveTo(helper.x, helper.y); x.lineTo(car.x, car.y); x.stroke(); x.setLineDash([]); });
    runtime.helpers.forEach(hp => { const hr = SENSOR_SPECS[hp.sensor].range; if (hr) { x.strokeStyle = "rgba(101,215,255,.15)"; x.lineWidth = 1; x.beginPath(); x.arc(hp.x, hp.y, Math.min(hr, 120), 0, Math.PI * 2); x.stroke(); } x.save(); x.translate(hp.x, hp.y); x.rotate(hp.angle); x.fillStyle = hp.role === "scout" ? "#65d7ff" : "#ffb85c"; x.beginPath(); x.moveTo(12, 0); x.lineTo(-8, -7); x.lineTo(-8, 7); x.closePath(); x.fill(); x.restore(); });
    x.save(); x.translate(car.x, car.y); x.rotate(car.angle); x.shadowColor = "#c4ff5c"; x.shadowBlur = 16; x.fillStyle = "#c4ff5c"; x.beginPath(); x.roundRect(-20, -12, 40, 24, 8); x.fill(); x.shadowBlur = 0; x.fillStyle = "#08100e"; x.fillRect(2, -8, 12, 16); x.fillStyle = "#e7ffbc"; x.fillRect(15, -7, 6, 14); x.restore();
  }, [course, car, runtime, sensor, size]);
  const pos = (e: React.PointerEvent) => { const r = canvas.current!.getBoundingClientRect(); return { x: clamp((e.clientX - r.left) / r.width * W, 25, W - 25), y: clamp((e.clientY - r.top) / r.height * H, 25, H - 25) }; };
  const edit = (p: Point) => { if (tool === "gate") setCourse({ ...course, gates: [...course.gates, { ...p, r: 34 }] }); else if (tool === "obstacle") setCourse({ ...course, obstacles: [...course.obstacles, { ...p, r: 46 }] }); else if (tool === "start") setCourse({ ...course, start: { ...p, angle: -Math.PI / 2 } }); else if (tool === "finish") setCourse({ ...course, finish: { ...p, r: 40 } }); else if (tool === "erase") setCourse({ ...course, gates: course.gates.filter(g => Math.hypot(g.x - p.x, g.y - p.y) > 55), obstacles: course.obstacles.filter(o => Math.hypot(o.x - p.x, o.y - p.y) > o.r + 18) }); };
  const down = (e: React.PointerEvent) => { canvas.current?.setPointerCapture(e.pointerId); drag.current = true; const p = pos(e); if (tool === "drive") { onManual(); setControl({ steer: clamp((p.x / W - .5) * 2, -1, 1), throttle: clamp((.65 - p.y / H) * 2, -1, 1) }); } else edit(p); };
  const move = (e: React.PointerEvent) => { if (!drag.current || tool !== "drive") return; const p = pos(e); onManual(); setControl({ steer: clamp((p.x / W - .5) * 2, -1, 1), throttle: clamp((.65 - p.y / H) * 2, -1, 1) }); };
  const up = () => { drag.current = false; if (tool === "drive") setControl({ ...control, steer: 0, throttle: 0 }); };
  return <div className="course-wrap" ref={ref}><canvas ref={canvas} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} aria-label="Course canvas" /><div className="canvas-hint">{tool === "drive" ? "DRAG: left/right steers · up accelerates" : `TAP TO PLACE ${tool.toUpperCase()}`}</div><div className="legend"><span><i className="driver-dot" />DRIVER</span>{runtime.helpers.length > 0 && <span><i className="helper-dot" />HELPERS</span>}{runtime.messages.length > 0 && <span><i className="link-dot" />PACKET</span>}</div></div>;
}

function Meter({ label, value, color = "#c4ff5c", suffix = "%" }: { label: string; value: number; color?: string; suffix?: string }) { return <div className="meter"><span>{label}</span><i><b style={{ width: `${clamp(value, 0, 100)}%`, background: color }} /></i><strong>{Math.round(value)}{suffix}</strong></div>; }
function EnergyBar({ label, value, total, color }: { label: string; value: number; total: number; color: string }) { return <div className="energy-row"><span>{label}</span><i><b style={{ width: `${total ? value / total * 100 : 0}%`, background: color }} /></i><strong>{value.toFixed(1)}</strong></div>; }

export default function Lab() {
  const [course, setCourseState] = useState<Course>(defaultCourse), courseRef = useRef(course);
  const [net, setNet] = useState<Network>(() => createNetwork()), netRef = useRef(net);
  const [team, setTeam] = useState<Team>(() => createTeam(net)), teamRef = useRef(team);
  const [car, setCarState] = useState<Car>(() => makeCar(course)), carRef = useRef(car);
  const [runtime, setRuntime] = useState<TeamRuntime>(() => createTeamRuntime(team, course, car)), runtimeRef = useRef(runtime);
  const resetCar = (c = courseRef.current, t = teamRef.current) => { const nextCar = makeCar(c), nextRuntime = createTeamRuntime(t, c, nextCar); carRef.current = nextCar; runtimeRef.current = nextRuntime; setCarState({ ...nextCar, energyLedger: { ...nextCar.energyLedger } }); setRuntime({ helpers: nextRuntime.helpers.map(h => ({ ...h })), messages: [] }); };
  const setCourse = (c: Course) => { courseRef.current = c; setCourseState(c); resetCar(c); };
  const publishRun = () => { const c = carRef.current, r = runtimeRef.current; setCarState({ ...c, energyLedger: { ...c.energyLedger } }); setRuntime({ helpers: r.helpers.map(h => ({ ...h })), messages: r.messages.map(m => ({ ...m })) }); };
  const [mode, setMode] = useState<Mode>("design"), [tool, setTool] = useState<Tool>("drive"), [running, setRunning] = useState(false), [control, setControlState] = useState<Control>({ steer: 0, throttle: 0 }), controlRef = useRef(control);
  const setControl = (c: Control) => { controlRef.current = c; setControlState(c); };
  const [samples, setSamples] = useState<ReturnType<typeof coachSamples>>([]), samplesRef = useRef(samples), [loss, setLoss] = useState<number | null>(null), [decision, setDecision] = useState<Decision>(emptyDecision), [inputMode, setInputMode] = useState<"idle" | "tilt" | "touch">("idle"), [toast, setToast] = useState("");
  const [width, setWidth] = useState(12), [depth, setDepth] = useState(2), [activation, setActivation] = useState<Activation>("tanh"), [lineage, setLineage] = useState(1), [runs, setRuns] = useState<History[]>([]);
  const [autoRunning, setAutoRunning] = useState(false), [autoGeneration, setAutoGeneration] = useState(0), [autoGenerations, setAutoGenerations] = useState(3), [population, setPopulation] = useState(6), [scenarios, setScenarios] = useState(2), [variation, setVariation] = useState(.18), [autoHistory, setAutoHistory] = useState<GenerationRow[]>([]), [holdout, setHoldout] = useState<Score | null>(null);
  const notify = (s: string) => { setToast(s); window.setTimeout(() => setToast(""), 2200); };

  useEffect(() => { const id = window.setTimeout(() => { try { const raw = localStorage.getItem("agent_forge_v2"); if (!raw) return; const saved = JSON.parse(raw); if (saved.course) { courseRef.current = saved.course; setCourseState(saved.course); } if (saved.samples) { samplesRef.current = saved.samples; setSamples(saved.samples); } if (saved.net?.sizes?.[0] === 12) { netRef.current = saved.net; setNet(saved.net); } if (saved.team?.driver?.sizes?.[0] === 12) { const restored = { ...saved.team, driverSensor: saved.team.driverSensor ?? "radar", helpers: (saved.team.helpers ?? []).map((h: Team["helpers"][number]) => ({ ...h, sensor: h.sensor ?? "radar" })) }; teamRef.current = restored; setTeam(restored); resetCar(saved.course ?? courseRef.current, restored); } } catch { /* ignore malformed local state */ } }, 0); return () => window.clearTimeout(id); }, []);
  useEffect(() => { const t = setTimeout(() => { try { localStorage.setItem("agent_forge_v2", JSON.stringify({ course, samples, net, team })); } catch { /* local-only persistence can be unavailable */ } }, 400); return () => clearTimeout(t); }, [course, samples, net, team]);

  const onManual = () => { if (mode !== "teach") { setMode("teach"); resetCar(); } if (!running) setRunning(true); setInputMode("touch"); };
  const startMode = (next: Mode) => { setMode(next); setTool("drive"); resetCar(); setRunning(next === "evaluate"); if (next === "evaluate") notify("Learning frozen. Tools now spend real energy."); };
  useEffect(() => {
    if (!running) return; let frame = 0, last = performance.now(), acc = 0;
    const loop = (now: number) => { const dt = Math.min(.035, (now - last) / 1000); last = now; const c = carRef.current; let input: number[], ctl = controlRef.current, packet: MessagePacket | undefined, update = "Weights frozen", result;
      if (mode === "evaluate") { const teamResult = stepTeam(courseRef.current, c, teamRef.current, runtimeRef.current, dt); input = teamResult.input; ctl = teamResult.control; result = teamResult.result; packet = teamResult.packet; controlRef.current = ctl; }
      else { input = observe(courseRef.current, c, teamRef.current.driverSensor); if (mode === "teach") { samplesRef.current.push({ input: [...input], output: [ctl.steer, ctl.throttle] }); if (samplesRef.current.length > 1800) samplesRef.current.shift(); update = "Demonstration saved"; } result = stepCar(courseRef.current, c, ctl, dt); }
      const reward = result.finished ? 1 : result.hit ? -.35 : result.gate ? .35 : result.progress - .001 * Math.abs(ctl.steer); acc += dt;
      if (acc > .09) { acc = 0; publishRun(); if (mode === "teach") setSamples([...samplesRef.current]); setDecision({ observation: packet ? `${packet.role} packet · obstacle ${Math.round(packet.distance)}u away · ${Math.round(packet.confidence * 100)}% confidence` : `Gate ${Math.min(c.gate + 1, courseRef.current.gates.length + 1)} · bearing ${(Math.atan2(input[0], input[1]) * 180 / Math.PI).toFixed(0)}° · clearance ${Math.round(input[5] * 100)}%`, action: `Steer ${ctl.steer >= 0 ? "right" : "left"} ${Math.abs(ctl.steer).toFixed(2)} · throttle ${ctl.throttle.toFixed(2)}`, result: result.finished ? "Goal reached" : result.hit ? "Collision" : result.gate ? "Gate cleared" : result.progress > 0 ? "Moved closer" : "Moved away", reward, update, inputs: input, outputs: [ctl.steer, ctl.throttle] }); }
      if (c.complete) { setRunning(false); setRuns(r => [{ label: mode === "teach" ? "Human" : `G${teamRef.current.generation} team`, score: score(c, courseRef.current) }, ...r].slice(0, 4)); notify(mode === "teach" ? "Demonstration complete" : "Frozen evaluation complete"); return; }
      frame = requestAnimationFrame(loop);
    }; frame = requestAnimationFrame(loop); return () => cancelAnimationFrame(frame);
  }, [running, mode]);

  const enableTilt = async () => { try { const Orientation = DeviceOrientationEvent as typeof DeviceOrientationEvent & { requestPermission?: () => Promise<string> }; if (Orientation.requestPermission && await Orientation.requestPermission() !== "granted") throw new Error(); window.addEventListener("deviceorientation", e => { setControl({ steer: clamp((e.gamma || 0) / 24, -1, 1), throttle: clamp(-(e.beta || 0) / 28, -1, 1) }); setInputMode("tilt"); }); startMode("teach"); setRunning(true); notify("Tilt connected — tip forward to drive"); } catch { setInputMode("touch"); startMode("teach"); notify("Tilt unavailable — drag on the course to drive"); } };
  const buildNet = () => { const n = createNetwork(width, depth, activation), next = createTeam(n); netRef.current = n; teamRef.current = next; setNet(n); setTeam(next); setLoss(null); setLineage(1); setAutoHistory([]); setHoldout(null); resetCar(courseRef.current, next); notify("Fresh untrained agent created"); };
  const doTrain = () => { if (samplesRef.current.length < 30) { notify("Record or load at least 30 coaching moments"); return; } const copy = cloneNetwork(netRef.current), l = train(copy, samplesRef.current, 22, .012), next = { ...teamRef.current, driver: copy }; netRef.current = copy; teamRef.current = next; setNet(copy); setTeam(next); setLoss(l); notify(`Training complete · loss ${l.toFixed(3)}`); };
  const addCoach = () => { const added = coachSamples(courseRef.current, 700); samplesRef.current = [...samplesRef.current, ...added].slice(-1800); setSamples([...samplesRef.current]); notify(`${added.length} coach moments loaded`); };
  const mutate = () => { const n = cloneNetwork(netRef.current, .09), next = { ...teamRef.current, id: `manual_${Date.now()}`, generation: teamRef.current.generation + 1, parentId: teamRef.current.id, driver: n }; netRef.current = n; teamRef.current = next; setNet(n); setTeam(next); setLineage(next.generation); notify("Mutated child is now active"); };
  const equipSensor = (sensor: SensorKind) => { const next = { ...teamRef.current, driverSensor: sensor }; teamRef.current = next; setTeam(next); resetCar(courseRef.current, next); notify(`${SENSOR_SPECS[sensor].label} equipped`); };
  const seedHelper = () => { if (teamRef.current.helpers.length >= 2) { notify("Two-helper limit reached"); return; } const role: HelperRole = teamRef.current.helpers.some(h => h.role === "scout") ? "finisher" : "scout", next = { ...teamRef.current, helpers: [...teamRef.current.helpers, { id: `${role}_${Date.now()}`, role, sensor: "radar" as SensorKind, network: cloneNetwork(netRef.current, .12) }] }; teamRef.current = next; setTeam(next); resetCar(courseRef.current, next); notify(`${role} helper seeded — auto-training may keep or remove it`); };
  const clearHelpers = () => { const next = { ...teamRef.current, helpers: [] }; teamRef.current = next; setTeam(next); resetCar(courseRef.current, next); notify("Helpers removed from this baseline"); };
  const runAuto = async () => { if (autoRunning) return; setRunning(false); setMode("auto"); setAutoRunning(true); setAutoGeneration(0); setAutoHistory([]); setHoldout(null); let parent = teamRef.current; for (let g = 1; g <= autoGenerations; g++) { await new Promise<void>(resolve => window.setTimeout(resolve, 25)); const result = evolveGeneration(parent, courseRef.current, parent.generation + 1, population, scenarios, variation, 250000); parent = result.team; setAutoGeneration(g); setAutoHistory(h => [...h, { generation: parent.generation, fitness: result.fitness, score: result.score, helpers: parent.helpers.length, parameters: result.parameters, sensor: parent.driverSensor, team: parent.helpers.map(x => x.role[0].toUpperCase()).join("+") || "solo" }]); setDecision({ observation: `${population} descendants × ${scenarios} altered courses`, action: "Promote best completed, efficient team", result: `${Math.round(result.score.completion * 100)}% complete · ${Math.round(result.score.efficiency)}% route efficiency`, reward: result.fitness, update: `G${parent.generation} kept · ${SENSOR_SPECS[parent.driverSensor].label} · ${parent.helpers.length} helper${parent.helpers.length === 1 ? "" : "s"}`, inputs: [], outputs: [] }); }
    teamRef.current = parent; netRef.current = parent.driver; setTeam(parent); setNet(parent.driver); setLineage(parent.generation); resetCar(courseRef.current, parent); const unseen = evaluateTeam(parent, varyCourse(courseRef.current, 99173, Math.min(.38, variation + .1))).score; setHoldout(unseen); setAutoRunning(false); notify(`Generation ${parent.generation} promoted · ${SENSOR_SPECS[parent.driverSensor].label} · ${parent.helpers.length} helpers`);
  };

  const scores = useMemo(() => score(car, course), [car, course]), params = teamParameters(team), plannedParams = (12 + 1) * width + Math.max(0, depth - 1) * (width + 1) * width + (width + 1) * 2, energyMax = Math.max(1, ...Object.values(car.energyLedger));
  return <main>{toast && <div className="toast">{toast}</div>}
    <header className="appbar"><div className="wordmark"><i>F</i><span><b>AGENT FORGE</b><small>TEACH · EVOLVE · VERIFY</small></span></div><div className="phase"><button className={mode === "design" ? "active" : ""} onClick={() => startMode("design")}><b>1</b> BUILD</button><button className={mode === "teach" ? "active" : ""} onClick={() => startMode("teach")}><b>2</b> TEACH</button><button className={mode === "auto" ? "active" : ""} onClick={() => startMode("auto")}><b>3</b> AUTO</button><button className={mode === "evaluate" ? "active" : ""} onClick={() => startMode("evaluate")}><b>4</b> TEST</button></div><span className="local">● LOCAL / SAVED</span></header>
    <section className="intro"><div><span className="eyebrow">RESOURCE-AWARE MACHINE LEARNING</span><h1>Reach the goal.<br /><em>Spend less to do it.</em></h1></div><p>Every sensor scan, helper movement, message, inference, and turn draws energy. Auto-training must finish the course first—then discover the cheapest capable team.</p></section>
    <section className="workspace"><article className="arena"><div className="arena-head"><span>{mode === "design" ? "COURSE BUILDER" : mode === "teach" ? "HUMAN DEMONSTRATION" : mode === "auto" ? "AUTOMATED TRAINING ARENA" : "FROZEN EVALUATION"}</span><b>{autoRunning ? `● GENERATION ${autoGeneration + 1}` : running ? "● RUNNING" : "○ PAUSED"}</b></div><CourseCanvas course={course} setCourse={setCourse} car={car} runtime={runtime} sensor={team.driverSensor} tool={tool} control={control} setControl={setControl} onManual={onManual} />
      {mode === "design" ? <div className="toolrow">{(["drive", "gate", "obstacle", "start", "finish", "erase"] as Tool[]).map(t => <button className={tool === t ? "active" : ""} key={t} onClick={() => setTool(t)}>{t}</button>)}<button onClick={() => setCourse(defaultCourse())}>SLALOM</button><button onClick={() => setCourse(blankCourse())}>CLEAR</button></div> : mode === "auto" ? <div className="drivebar auto-bar"><button className="primary" disabled={autoRunning} onClick={runAuto}>{autoRunning ? `TRAINING ${autoGeneration}/${autoGenerations}` : "RUN AUTO TRAINING"}</button><span>{population} TEAMS × {scenarios} COURSES × {autoGenerations} GENERATIONS</span></div> : <div className="drivebar"><button className="primary" onClick={() => setRunning(!running)}>{running ? "PAUSE" : "START"}</button><button onClick={() => resetCar()}>RESET RUN</button>{mode === "teach" && <button className="tilt" onClick={enableTilt}>USE PHONE TILT</button>}<span>{mode === "evaluate" ? `${SENSOR_SPECS[team.driverSensor].label.toUpperCase()} · ${team.helpers.length} HELPERS · LEARNING FROZEN` : inputMode === "tilt" ? "IMU CONNECTED" : inputMode === "touch" ? "TOUCH STEERING" : "DRAG OR ENABLE TILT"}</span></div>}
    </article>
      <aside className="rail">
        <article className="panel mission"><header><span>MISSION PRIORITY</span><b>Finish → safe → efficient</b></header><p>Stopping saves energy but earns nothing. Route and energy scores unlock only after the ordered gates and goal are completed.</p><div><Meter label="Completion" value={scores.completion * 100} /><Meter label="Collision safety" value={scores.collisions} color="#65d7ff" /><Meter label="Route efficiency" value={scores.efficiency} color="#da8cff" /><Meter label="Energy reserve" value={scores.energy} color="#ffb85c" /></div></article>
        <article className="panel tools"><header><span>DRIVER SENSOR</span><b>{SENSOR_SPECS[team.driverSensor].cost.toFixed(2)} draw / sec</b></header><div className="sensor-grid">{(Object.keys(SENSOR_SPECS) as SensorKind[]).map(kind => <button key={kind} className={team.driverSensor === kind ? "active" : ""} onClick={() => equipSensor(kind)}><span>{SENSOR_SPECS[kind].label}</span><small>{SENSOR_SPECS[kind].description}</small><b>{SENSOR_SPECS[kind].range ? `${SENSOR_SPECS[kind].range}u` : "0 draw"}</b></button>)}</div><p>Auto-training can replace this sensor when a cheaper—or more capable—configuration wins.</p></article>
        <article className="panel energy"><header><span>ENERGY LEDGER</span><b>{car.energy.toFixed(1)} units used</b></header><div><EnergyBar label="Propulsion" value={car.energyLedger.propulsion} total={energyMax} color="#c4ff5c" /><EnergyBar label="Sensing" value={car.energyLedger.sensing} total={energyMax} color="#da8cff" /><EnergyBar label="Helper bodies" value={car.energyLedger.helpers} total={energyMax} color="#65d7ff" /><EnergyBar label="Messages" value={car.energyLedger.comms} total={energyMax} color="#ffb85c" /><EnergyBar label="Compute" value={car.energyLedger.compute} total={energyMax} color="#ff6254" /></div></article>
        <article className="panel brain"><header><span>AGENT · GENERATION {lineage}</span><b>{net.sizes.join(" × ")}</b></header><div className="brain-grid"><label>WIDTH<input type="range" min="6" max="128" step="2" value={width} onChange={e => setWidth(+e.target.value)} /><b>{width}</b></label><label>DEPTH<input type="range" min="1" max="4" value={depth} onChange={e => setDepth(+e.target.value)} /><b>{depth}</b></label><label>ACTIVATION<select value={activation} onChange={e => setActivation(e.target.value as Activation)}><option>tanh</option><option>relu</option><option>sigmoid</option></select></label></div><div className="budget"><span>PLANNED BRAIN</span><b>{plannedParams.toLocaleString()} parameters</b><i><em style={{ width: `${Math.min(100, plannedParams / 2500)}%` }} /></i><small>250,000 shared ecosystem budget</small></div><div className="brain-actions"><button onClick={buildNet}>NEW BRAIN</button><button onClick={mutate}>CLONE + MUTATE</button></div></article>
        {mode === "auto" ? <article className="panel autolab"><header><span>AUTO TRAIN</span><b>{autoRunning ? `${autoGeneration}/${autoGenerations}` : "READY"}</b></header><div className="auto-settings"><label>GENERATIONS<input type="range" min="3" max="20" value={autoGenerations} onChange={e => setAutoGenerations(+e.target.value)} /><b>{autoGenerations}</b></label><label>POPULATION<input type="range" min="6" max="18" value={population} onChange={e => setPopulation(+e.target.value)} /><b>{population}</b></label><label>SCENARIOS<input type="range" min="2" max="8" value={scenarios} onChange={e => setScenarios(+e.target.value)} /><b>{scenarios}</b></label><label>VARIATION<input type="range" min=".05" max=".35" step=".01" value={variation} onChange={e => setVariation(+e.target.value)} /><b>{Math.round(variation * 100)}%</b></label></div><button className="primary wide" disabled={autoRunning} onClick={runAuto}>{autoRunning ? "EVOLUTION RUNNING" : "START GENERATIONS"}</button><p>Each descendant can change its sensor, create up to two helpers, or remove them. Completion dominates; efficiency decides between capable teams.</p></article> : <article className="panel teachbox"><header><span>TRAINING SET</span><b>{samples.length.toLocaleString()} moments</b></header><p>A moment pairs what the agent could observe with the steering and throttle you chose.</p><div><button onClick={addCoach}>LOAD COACH LAP</button><button className="primary" onClick={doTrain}>TRAIN AGENT</button></div>{loss !== null && <small>LAST TRAINING LOSS <b>{loss.toFixed(4)}</b></small>}</article>}
        <article className="panel team"><header><span>ACTIVE TEAM</span><b>{params.toLocaleString()} / 250,000</b></header><div className="team-list"><div><i className="driver" /><span><b>DRIVER · {SENSOR_SPECS[team.driverSensor].label.toUpperCase()}</b><small>Steering + throttle policy</small></span><strong>{parameterCount(team.driver).toLocaleString()}</strong></div>{team.helpers.map(h => <div key={h.id}><i className={h.role} /><span><b>{h.role.toUpperCase()} · {SENSOR_SPECS[h.sensor].label.toUpperCase()}</b><small>{h.role === "scout" ? "Moves ahead and reports obstacles" : "Guards the final approach"}</small></span><strong>{parameterCount(h.network).toLocaleString()}</strong></div>)}{!team.helpers.length && <p>Solo agent. Auto-training may create helpers only if their information repays their energy cost.</p>}</div><div className="team-actions"><button onClick={seedHelper}>SEED HELPER</button>{team.helpers.length > 0 && <button onClick={clearHelpers}>CLEAR HELPERS</button>}</div></article>
      </aside>
    </section>
    <section className="evidence"><article className="panel decision"><header><span>LATEST DECISION — NO MYSTERY DOTS</span><b>{mode === "evaluate" ? "LEARNING OFF" : mode === "teach" ? "RECORDING" : mode === "auto" ? "POPULATION TRAINING" : "IDLE"}</b></header><div>{[["01 · OBSERVATION", decision.observation], ["02 · ACTION", decision.action], ["03 · RESULT", decision.result], ["04 · REWARD", decision.reward.toFixed(3)], ["05 · LEARNING UPDATE", decision.update]].map(([k, v]) => <section key={k}><span>{k}</span><b>{v}</b></section>)}</div></article>
      <article className="panel packets"><header><span>HELPER RADIO</span><b>{runtime.messages.length ? `${runtime.messages.length} LIVE PACKETS` : "QUIET"}</b></header>{runtime.messages.length ? runtime.messages.map((m, i) => <div className="packet" key={`${m.from}_${i}`}><i className={m.role} /><b>{m.role.toUpperCase()}</b><span>{Math.round(m.distance)}u</span><span>size {Math.round(m.size)}</span><span>{Math.round(m.confidence * 100)}% conf</span><span>{m.age.toFixed(1)}s old</span></div>) : <p className="empty">Helpers send only bearing, distance, obstacle size, confidence, and message age—never a hidden route.</p>}</article>
      <article className="panel comparison"><header><span>RUN HISTORY</span><b>ORACLE SCORES AFTER FINISH</b></header>{runs.length ? runs.map((r, i) => <div className="run" key={i}><b>{r.label}</b><span>{Math.round(r.score.completion * 100)}% complete</span><span>{Math.round(r.score.efficiency)}% efficient</span><span>{Math.round(r.score.collisions)} safety</span><span>{Math.round(r.score.energy)} energy</span></div>) : <p className="empty">Finish a human or agent run to compare it with the hidden shortest feasible route.</p>}</article>
      <article className="panel generations"><header><span>GENERATION LEDGER</span><b>{holdout ? `UNSEEN: ${Math.round(holdout.completion * 100)}% COMPLETE · ${Math.round(holdout.efficiency)}% EFFICIENT` : "TRAIN COURSES ≠ TEST COURSE"}</b></header>{autoHistory.length ? <div className="generation-table"><div className="generation-row head"><span>GEN</span><span>FITNESS</span><span>COMPLETE</span><span>ROUTE</span><span>ENERGY</span><span>TOOLS</span><span>PARAMETERS</span></div>{autoHistory.map(row => <div className="generation-row" key={row.generation}><b>G{row.generation}</b><span>{row.fitness.toFixed(0)}</span><span>{Math.round(row.score.completion * 100)}%</span><span>{Math.round(row.score.efficiency)}%</span><span>{Math.round(row.score.energy)}</span><span>{SENSOR_SPECS[row.sensor].label} · {row.team}</span><span>{row.parameters.toLocaleString()}</span></div>)}</div> : <p className="empty">Auto-training records which brain, sensor, and helper economy each promoted champion chose.</p>}</article>
    </section><footer><b>AGENT FORGE / PROTOTYPE 03</b><span>Complete first · route oracle hidden · every tool has a cost</span></footer>
  </main>;
}
