export const MEANINGS = ["NORTH","NORTHEAST","EAST","SOUTHEAST","SOUTH","SOUTHWEST","WEST","NORTHWEST"] as const;
export const TOKENS = ["◈","●","▲","■","✦","⬟","◆","✚"] as const;
export type Challenge={level:number;meaningCount:number;tokenCount:number;channelNoise:number;rewardNoise:number;mastery:number};
export type Trace={id:number;target:number;sent:number;received:number|null;action:number;success:boolean;reward:number;senderProbabilities:number[];receiverProbabilities:number[];counterfactuals:number[][]};
export type Snapshot={sender:number[][];receiver:number[][];baseline:number;episodes:number;successes:number;recent:number[];chart:{episode:number;accuracy:number}[];traces:Trace[];seed:number};
export type Evaluation={mode:"intact"|"scrambled"|"silent";accuracy:number;trials:number};
const SIZE=8;
export function mulberry32(seed:number){let value=seed>>>0;return()=>{value+=0x6d2b79f5;let t=value;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}};
const matrix=(random:()=>number)=>Array.from({length:SIZE},()=>Array.from({length:SIZE},()=>(random()-.5)*.08));
export function createSnapshot(seed=Math.floor(Math.random()*1e6)):Snapshot{const random=mulberry32(seed);return{sender:matrix(random),receiver:matrix(random),baseline:0,episodes:0,successes:0,recent:[],chart:[{episode:0,accuracy:0}],traces:[],seed}};
export function enterChallenge(snapshot:Snapshot):Snapshot{return{...snapshot,recent:[],chart:[{episode:snapshot.episodes,accuracy:0}],traces:[]}};
export function softmax(logits:number[],temperature=1){const scaled=logits.map(v=>v/Math.max(.08,temperature)),max=Math.max(...scaled),exps=scaled.map(v=>Math.exp(v-max)),sum=exps.reduce((a,b)=>a+b,0);return exps.map(v=>v/sum)}
export function greedy(p:number[]){return p.reduce((best,value,index,array)=>value>array[best]?index:best,0)}
function choose(p:number[],random:()=>number){let cursor=random();for(let i=0;i<p.length;i++){cursor-=p[i];if(cursor<=0)return i}return p.length-1}
function update(row:number[],selected:number,p:number[],advantage:number,rate:number){for(let i=0;i<p.length;i++){const d=(i===selected?1:0)-p[i];row[i]=Math.max(-8,Math.min(8,row[i]+rate*advantage*d))}}
export function trainBatch(previous:Snapshot,count:number,rate:number,temperature:number,challenge:Challenge){
 const state:Snapshot={...previous,sender:previous.sender.map(r=>[...r]),receiver:previous.receiver.map(r=>[...r]),recent:[...previous.recent],chart:[...previous.chart],traces:[...previous.traces]},random=mulberry32(state.seed+state.episodes*7919+challenge.level*1009+17);
 for(let run=0;run<count;run++){const target=Math.floor(random()*challenge.meaningCount),senderP=softmax(state.sender[target].slice(0,challenge.tokenCount),temperature),sent=choose(senderP,random);let received:number|null=sent;if(random()<challenge.channelNoise)received=Math.floor(random()*challenge.tokenCount);const receiverP=softmax(state.receiver[received].slice(0,challenge.meaningCount),temperature),action=choose(receiverP,random),success=action===target,reward=success?.97:-.28,perceived=random()<challenge.rewardNoise?!success:success,learningReward=perceived?.97:-.28;
  state.baseline=state.baseline*.985+learningReward*.015;const advantage=learningReward-state.baseline;update(state.sender[target],sent,senderP,advantage,rate);update(state.receiver[received],action,receiverP,advantage,rate);state.episodes++;state.successes+=success?1:0;state.recent.push(success?1:0);if(state.recent.length>300)state.recent.shift();
  if(run===count-1){state.traces.unshift({id:state.episodes,target,sent,received,action,success,reward,senderProbabilities:senderP,receiverProbabilities:receiverP,counterfactuals:state.receiver.slice(0,challenge.tokenCount).map(row=>softmax(row.slice(0,challenge.meaningCount),.18))});state.traces=state.traces.slice(0,16)}
  if(state.episodes%100===0){const accuracy=state.recent.reduce((s,v)=>s+v,0)/Math.max(1,state.recent.length);state.chart.push({episode:state.episodes,accuracy:accuracy*100});state.chart=state.chart.slice(-80)}
 }return state
}
export function evaluate(snapshot:Snapshot,challenge:Challenge,mode:Evaluation["mode"],trials=800):Evaluation{const random=mulberry32(snapshot.seed+snapshot.episodes+mode.length*10007+challenge.level);let successes=0;for(let i=0;i<trials;i++){const target=Math.floor(random()*challenge.meaningCount),sent=greedy(softmax(snapshot.sender[target].slice(0,challenge.tokenCount),.12));let received:number|null=sent;if(mode==="silent")received=null;else if(mode==="scrambled")received=Math.floor(random()*challenge.tokenCount);else if(random()<challenge.channelNoise)received=Math.floor(random()*challenge.tokenCount);const action=received===null?Math.floor(random()*challenge.meaningCount):greedy(softmax(snapshot.receiver[received].slice(0,challenge.meaningCount),.12));if(action===target)successes++}return{mode,accuracy:successes/trials*100,trials}}
export function dictionary(snapshot:Snapshot,challenge:Challenge){return MEANINGS.slice(0,challenge.meaningCount).map((meaning,target)=>{const p=softmax(snapshot.sender[target].slice(0,challenge.tokenCount),.18),tokenIndex=greedy(p),rp=softmax(snapshot.receiver[tokenIndex].slice(0,challenge.meaningCount),.18);return{meaning,token:TOKENS[tokenIndex],tokenIndex,confidence:p[tokenIndex]*100,interpretedAs:MEANINGS[greedy(rp)],interpretationConfidence:Math.max(...rp)*100}})}
export function rollingAccuracy(snapshot:Snapshot){return snapshot.recent.length?snapshot.recent.reduce((s,v)=>s+v,0)/snapshot.recent.length*100:0}
export function nextChallenge(current:Challenge):Challenge{if(current.meaningCount<8)return{...current,level:current.level+1,meaningCount:current.meaningCount+1,tokenCount:Math.max(current.tokenCount,current.meaningCount+1)};if(current.channelNoise<.25){const noise=+Math.min(.25,current.channelNoise+.025).toFixed(3);return{...current,level:current.level+1,channelNoise:noise,mastery:Math.max(72,92-noise*75)}}return{...current,level:current.level+1,rewardNoise:+Math.min(.2,current.rewardNoise+.01).toFixed(3),mastery:Math.max(70,current.mastery-.25)}}
