export const MEANINGS = ["NORTH", "NORTHEAST", "EAST", "SOUTHEAST", "SOUTH", "SOUTHWEST", "WEST", "NORTHWEST"] as const;
export const TOKENS = ["◈", "●", "▲", "■", "✦", "⬟", "◆", "✚"] as const;
export const COLORS = ["#a8ff60", "#87f7c7", "#ffc46b", "#9bb8ff", "#f7a7ff", "#ff8f78"];

export type Activation = "tanh" | "relu" | "sigmoid";
export type Genome = { hiddenLayers:number; width:number; activation:Activation; learningRate:number; exploration:number; mutation:number };
export type Network = { sizes:number[]; weights:number[][][] };
export type Agent = { id:string; name:string; color:string; parentId:string|null; generation:number; bornAt:number; genome:Genome; sender:Network; receiver:Network; trials:number; wins:number; fitness:number };
export type World = { id:string; name:string; meaningCount:number; tokenCount:number; channelNoise:number; rewardNoise:number; mastery:number; seed:number; generation:number; parentId:string|null };
export type Trace = { id:number; target:number; sent:number; received:number; action:number; success:boolean; actualReward:number; perceivedReward:number; advantage:number; senderProbabilities:number[]; receiverProbabilities:number[]; senderHidden:number[]; receiverHidden:number[] };
export type Run = { key:string; senderId:string; receiverId:string; worldId:string; episodes:number; successes:number; recent:number[]; baseline:number; chart:{episode:number;accuracy:number}[]; traces:Trace[]; bestAccuracy:number; masteredAt:number|null };
export type JournalEntry = { id:string; at:number; kind:"birth"|"mastery"|"world"|"mutation"; title:string; detail:string };
export type Lab = { version:3; agents:Agent[]; worlds:World[]; runs:Record<string,Run>; activeSenderId:string; activeReceiverId:string; activeWorldId:string; journal:JournalEntry[]; createdAt:number };
export type EvaluationMode = "intact"|"scrambled"|"silent";
export type Evaluation = { mode:EvaluationMode; accuracy:number; trials:number };

const INPUTS=8, OUTPUTS=8;
const clamp=(value:number,lo:number,hi:number)=>Math.max(lo,Math.min(hi,value));
export const uid=(prefix:string)=>`${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
export function mulberry32(seed:number){let value=seed>>>0;return()=>{value+=0x6d2b79f5;let t=value;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}
export function softmax(logits:number[],temperature=1){const scaled=logits.map(v=>v/Math.max(.06,temperature)),max=Math.max(...scaled),exps=scaled.map(v=>Math.exp(clamp(v-max,-30,30))),sum=exps.reduce((a,b)=>a+b,0);return exps.map(v=>v/sum)}
export function greedy(values:number[]){return values.reduce((best,value,index,array)=>value>array[best]?index:best,0)}
function choose(values:number[],random:()=>number){let cursor=random();for(let i=0;i<values.length;i++){cursor-=values[i];if(cursor<=0)return i}return values.length-1}
function oneHot(index:number){return Array.from({length:INPUTS},(_,i)=>i===index?1:0)}
function activate(value:number,kind:Activation){if(kind==="relu")return clamp(value,0,8);if(kind==="sigmoid")return 1/(1+Math.exp(-clamp(value,-20,20)));return Math.tanh(value)}
function derivative(value:number,kind:Activation){if(kind==="relu")return value>0?1:0;if(kind==="sigmoid"){const s=activate(value,kind);return s*(1-s)}const t=Math.tanh(value);return 1-t*t}

export function createNetwork(genome:Genome,random:()=>number):Network{const sizes=[INPUTS,...Array.from({length:genome.hiddenLayers},()=>genome.width),OUTPUTS];const weights=sizes.slice(1).map((outSize,layer)=>Array.from({length:outSize},()=>Array.from({length:sizes[layer]+1},()=>(random()-.5)*Math.sqrt(6/(sizes[layer]+outSize)))));return{sizes,weights}}
function cloneNetwork(network:Network):Network{return{sizes:[...network.sizes],weights:network.weights.map(layer=>layer.map(row=>[...row]))}}
function forward(network:Network,input:number[],activation:Activation,limit:number,temperature:number){const activations=[input],preacts:number[][]=[];let current=input;for(let l=0;l<network.weights.length;l++){const z=network.weights[l].map(row=>row[row.length-1]+current.reduce((sum,value,i)=>sum+value*row[i],0));preacts.push(z);current=l===network.weights.length-1?softmax(z.slice(0,limit),temperature):z.map(v=>activate(v,activation));activations.push(current)}return{probabilities:current,activations,preacts}}
function learn(network:Network,pass:ReturnType<typeof forward>,selected:number,advantage:number,rate:number,activation:Activation){let delta=pass.probabilities.map((p,i)=>clamp(advantage*((i===selected?1:0)-p),-2,2));for(let l=network.weights.length-1;l>=0;l--){const layer=network.weights[l],previous=pass.activations[l],old=layer.map(row=>[...row]);for(let out=0;out<delta.length;out++){for(let input=0;input<previous.length;input++)layer[out][input]=clamp(layer[out][input]+rate*delta[out]*previous[input],-6,6);layer[out][previous.length]=clamp(layer[out][previous.length]+rate*delta[out],-6,6)}if(l>0)delta=Array.from({length:previous.length},(_,input)=>clamp(delta.reduce((sum,value,out)=>sum+old[out][input]*value,0)*derivative(pass.preacts[l-1][input],activation),-4,4))}}

function makeAgent(name:string,color:string,genome:Genome,seed:number,parentId:string|null=null,generation=0):Agent{const random=mulberry32(seed);return{id:uid("agent"),name,color,parentId,generation,bornAt:Date.now(),genome,sender:createNetwork(genome,random),receiver:createNetwork(genome,random),trials:0,wins:0,fitness:0}}
export function createAgent(name:string,color:string,genome:Genome,seed=Math.floor(Math.random()*1e9)){return makeAgent(name,color,genome,seed)}
export function cloneAgent(parent:Agent,name:string,mutate:boolean){const random=mulberry32(Math.floor(Math.random()*1e9)),genome={...parent.genome};const child:Agent={...parent,id:uid("agent"),name,color:COLORS[(parent.generation+1)%COLORS.length],parentId:parent.id,generation:parent.generation+1,bornAt:Date.now(),genome,sender:cloneNetwork(parent.sender),receiver:cloneNetwork(parent.receiver),trials:0,wins:0,fitness:0};if(mutate){const mutateNet=(network:Network)=>network.weights.forEach(layer=>layer.forEach(row=>row.forEach((value,i)=>{if(random()<.35)row[i]=clamp(value+(random()-.5)*2*genome.mutation,-6,6)})));mutateNet(child.sender);mutateNet(child.receiver);child.genome.learningRate=clamp(child.genome.learningRate*(.85+random()*.3),.01,.35);child.genome.exploration=clamp(child.genome.exploration*(.85+random()*.3),.08,1.5)}return child}
export function rebuildAgent(agent:Agent,genome:Genome){const random=mulberry32(Math.floor(Math.random()*1e9));return{...agent,genome,sender:createNetwork(genome,random),receiver:createNetwork(genome,random),trials:0,wins:0,fitness:0}}

export function runKey(senderId:string,receiverId:string,worldId:string){return`${senderId}::${receiverId}::${worldId}`}
export function emptyRun(senderId:string,receiverId:string,worldId:string):Run{return{key:runKey(senderId,receiverId,worldId),senderId,receiverId,worldId,episodes:0,successes:0,recent:[],baseline:0,chart:[{episode:0,accuracy:0}],traces:[],bestAccuracy:0,masteredAt:null}}
export function rollingAccuracy(run:Run){return run.recent.length?run.recent.reduce((a,b)=>a+b,0)/run.recent.length*100:0}

export function createLab():Lab{const defaultGenome:Genome={hiddenLayers:1,width:8,activation:"tanh",learningRate:.04,exploration:.5,mutation:.18};const aster=makeAgent("Aster",COLORS[0],defaultGenome,81527),rune=makeAgent("Rune",COLORS[1],{...defaultGenome,width:12},41021);aster.id="agent_aster";rune.id="agent_rune";const worlds:World[]=[{id:"world_compass",name:"Hidden Compass",meaningCount:2,tokenCount:2,channelNoise:0,rewardNoise:0,mastery:92,seed:1701,generation:0,parentId:null},{id:"world_static",name:"Static Garden",meaningCount:4,tokenCount:4,channelNoise:.08,rewardNoise:.02,mastery:84,seed:2718,generation:1,parentId:"world_compass"}];return{version:3,agents:[aster,rune],worlds,runs:{},activeSenderId:aster.id,activeReceiverId:rune.id,activeWorldId:worlds[0].id,journal:[{id:"log_origin",at:0,kind:"birth",title:"Laboratory founded",detail:"Aster and Rune entered Hidden Compass with no shared vocabulary."}],createdAt:0}}

export function trainLab(previous:Lab,count:number):Lab{const lab:Lab={...previous,agents:previous.agents.map(a=>({...a,genome:{...a.genome},sender:cloneNetwork(a.sender),receiver:cloneNetwork(a.receiver)})),runs:{...previous.runs},journal:[...previous.journal]};const sender=lab.agents.find(a=>a.id===lab.activeSenderId)!,receiver=lab.agents.find(a=>a.id===lab.activeReceiverId)!,world=lab.worlds.find(w=>w.id===lab.activeWorldId)!;const key=runKey(sender.id,receiver.id,world.id),old=lab.runs[key]??emptyRun(sender.id,receiver.id,world.id),run:Run={...old,recent:[...old.recent],chart:[...old.chart],traces:[...old.traces]};const random=mulberry32(world.seed+run.episodes*7919+sender.generation*101+receiver.generation*307+17);for(let trial=0;trial<count;trial++){const target=Math.floor(random()*world.meaningCount),senderPass=forward(sender.sender,oneHot(target),sender.genome.activation,world.tokenCount,sender.genome.exploration),sent=choose(senderPass.probabilities,random),received=random()<world.channelNoise?Math.floor(random()*world.tokenCount):sent,receiverPass=forward(receiver.receiver,oneHot(received),receiver.genome.activation,world.meaningCount,receiver.genome.exploration),action=choose(receiverPass.probabilities,random),success=action===target,actualReward=success?1:-.25,perceivedSuccess=random()<world.rewardNoise?!success:success,perceivedReward=perceivedSuccess?1:-.25;run.baseline=run.baseline*.985+perceivedReward*.015;const advantage=perceivedReward-run.baseline;learn(sender.sender,senderPass,sent,advantage,sender.genome.learningRate,sender.genome.activation);learn(receiver.receiver,receiverPass,action,advantage,receiver.genome.learningRate,receiver.genome.activation);run.episodes++;run.successes+=success?1:0;run.recent.push(success?1:0);if(run.recent.length>300)run.recent.shift();sender.trials++;receiver.trials++;if(success){sender.wins++;receiver.wins++}sender.fitness+=actualReward;receiver.fitness+=actualReward;if(trial===count-1){run.traces.unshift({id:run.episodes,target,sent,received,action,success,actualReward,perceivedReward,advantage,senderProbabilities:senderPass.probabilities,receiverProbabilities:receiverPass.probabilities,senderHidden:senderPass.activations[1]??senderPass.probabilities,receiverHidden:receiverPass.activations[1]??receiverPass.probabilities});run.traces=run.traces.slice(0,24)}if(run.episodes%100===0){const score=rollingAccuracy(run);run.chart.push({episode:run.episodes,accuracy:score});run.chart=run.chart.slice(-100);run.bestAccuracy=Math.max(run.bestAccuracy,score);if(!run.masteredAt&&run.recent.length>=250&&score>=world.mastery){run.masteredAt=run.episodes;lab.journal.unshift({id:uid("log"),at:Date.now(),kind:"mastery",title:`${sender.name} × ${receiver.name} mastered ${world.name}`,detail:`${score.toFixed(1)}% accuracy after ${run.episodes.toLocaleString()} trials.`})}}}lab.runs[key]=run;lab.journal=lab.journal.slice(0,80);return lab}

function act(sender:Agent,receiver:Agent,world:World,target:number,random:()=>number,mode:EvaluationMode){const sp=forward(sender.sender,oneHot(target),sender.genome.activation,world.tokenCount,.08).probabilities,sent=greedy(sp),received=mode==="silent"?-1:mode==="scrambled"?Math.floor(random()*world.tokenCount):random()<world.channelNoise?Math.floor(random()*world.tokenCount):sent;if(received<0)return{sent,received,action:Math.floor(random()*world.meaningCount),senderProbabilities:sp,receiverProbabilities:Array(world.meaningCount).fill(1/world.meaningCount)};const rp=forward(receiver.receiver,oneHot(received),receiver.genome.activation,world.meaningCount,.08).probabilities;return{sent,received,action:greedy(rp),senderProbabilities:sp,receiverProbabilities:rp}}
export function evaluate(sender:Agent,receiver:Agent,world:World,mode:EvaluationMode,trials=500):Evaluation{const random=mulberry32(world.seed+sender.trials+receiver.trials+mode.length*10007);let successes=0;for(let i=0;i<trials;i++){const target=Math.floor(random()*world.meaningCount);if(act(sender,receiver,world,target,random,mode).action===target)successes++}return{mode,accuracy:successes/trials*100,trials}}
export function crossPlay(agents:Agent[],world:World){return agents.map(sender=>agents.map(receiver=>evaluate(sender,receiver,world,"intact",180).accuracy))}
export function dictionary(sender:Agent,receiver:Agent,world:World){return MEANINGS.slice(0,world.meaningCount).map((meaning,target)=>{const sp=forward(sender.sender,oneHot(target),sender.genome.activation,world.tokenCount,.08).probabilities,tokenIndex=greedy(sp),rp=forward(receiver.receiver,oneHot(tokenIndex),receiver.genome.activation,world.meaningCount,.08).probabilities;return{meaning,token:TOKENS[tokenIndex],tokenIndex,confidence:sp[tokenIndex]*100,interpretedAs:MEANINGS[greedy(rp)],interpretationConfidence:Math.max(...rp)*100}})}
export function executeMission(text:string,sender:Agent,receiver:Agent,world:World){const normalized=text.toUpperCase().replace(/[ -]/g,"");let target=-1;for(let i=world.meaningCount-1;i>=0;i--)if(normalized.includes(MEANINGS[i])){target=i;break}if(target<0)return{ok:false as const,message:"The local parser needs one active direction."};const random=mulberry32(world.seed+sender.trials+text.length*41),result=act(sender,receiver,world,target,random,"intact");return{ok:true as const,target,...result,success:result.action===target}}
export function networkParameterCount(agent:Agent){return agent.sender.weights.concat(agent.receiver.weights).reduce((sum,layer)=>sum+layer.reduce((s,row)=>s+row.length,0),0)}
